<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>21e096c0-1cdb-4e7d-a04a-0fab22d6fb30</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <None Include="DTOs\AuthDTOs\ResetPasswordDTO.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LanguageExt.Core" Version="4.4.9" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Expensify.DataAccessLayer\Expensify.DataAccessLayer.csproj" />
  </ItemGroup>
</Project>
