// <auto-generated />
using System;
using System.Collections.Generic;
using Expensify.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Expensify.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260722173809_DDL_AddIconToAccountTable")]
    partial class DDL_AddIconToAccountTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.BudgetingSchema.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint")
                        .HasColumnName("create_date");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<long?>("EndDate")
                        .HasColumnType("bigint")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deletion_indicator");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shared");

                    b.Property<Guid>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<decimal>("LimitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("limit_amount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasColumnOrder(2);

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("Period")
                        .HasColumnType("integer")
                        .HasColumnName("period");

                    b.Property<long>("StartDate")
                        .HasColumnType("bigint")
                        .HasColumnName("start_date");

                    b.Property<long>("UpdatedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_budgets");

                    b.HasIndex("OwnerUserId", "IsActive")
                        .HasDatabaseName("ix_budgets_owner_user_id_is_active");

                    b.HasIndex("OwnerUserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_budgets_owner_user_id_name");

                    b.ToTable("budgets", "budgeting");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.BudgetingSchema.BudgetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<decimal?>("CategoryLimitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("category_limit_amount");

                    b.HasKey("Id")
                        .HasName("pk_budget_categories");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_budget_categories_category_id");

                    b.HasIndex("BudgetId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ux_budget_categories_budget_id_category_id");

                    b.ToTable("budget_categories", "budgeting");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.BudgetingSchema.BudgetMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint")
                        .HasColumnName("create_date");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deletion_indicator");

                    b.Property<long>("JoinedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("joined_date");

                    b.Property<Guid>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasColumnOrder(2);

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<long>("UpdatedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_budget_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_budget_members_user_id");

                    b.HasIndex("BudgetId", "IsActive")
                        .HasDatabaseName("ix_budget_members_budget_id_is_active");

                    b.HasIndex("BudgetId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_budget_members_budget_id_user_id");

                    b.ToTable("budget_members", "budgeting");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<Guid>("AccountTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_type_id");

                    b.Property<decimal>("AvailableBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("available_balance");

                    b.Property<long?>("ClosedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("closed_date");

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint")
                        .HasColumnName("create_date");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("credit_limit");

                    b.Property<int>("CurrencyCode")
                        .HasColumnType("integer")
                        .HasColumnName("currency_code");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_balance");

                    b.Property<string>("Icon")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("icon");

                    b.Property<bool>("IncludeInNetWorth")
                        .HasColumnType("boolean")
                        .HasColumnName("include_in_net_worth");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("institution_name");

                    b.Property<decimal?>("InterestRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("interest_rate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deletion_indicator");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<string>("LastFourDigits")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("last_four_digits");

                    b.Property<Guid>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasColumnOrder(2);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<long>("UpdatedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("AccountTypeId")
                        .HasDatabaseName("ix_accounts_account_type_id");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("ix_accounts_user_id_is_active");

                    b.HasIndex("UserId", "IsHidden")
                        .HasDatabaseName("ix_accounts_user_id_is_hidden");

                    b.ToTable("accounts", "finance");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.AccountType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint")
                        .HasColumnName("create_date");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deletion_indicator");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_default");

                    b.Property<Guid>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasColumnOrder(2);

                    b.Property<long>("UpdatedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_date");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_account_types");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("ix_account_types_user_id_is_active");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_account_types_user_id_name");

                    b.ToTable("account_types", "finance");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f8332b7-cf15-4c41-b1b5-a85022859dd8"),
                            CreateDate = 0L,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Standard checking account.",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemDefault = true,
                            LastUpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Checking",
                            UpdatedDate = 0L
                        },
                        new
                        {
                            Id = new Guid("21d970f4-bda1-48c5-8b04-f38408508238"),
                            CreateDate = 0L,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Standard savings account.",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemDefault = true,
                            LastUpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Savings",
                            UpdatedDate = 0L
                        },
                        new
                        {
                            Id = new Guid("c524f6bf-b7da-4985-a1af-f76222dfc89c"),
                            CreateDate = 0L,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Credit card or revolving credit account.",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemDefault = true,
                            LastUpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Credit Card",
                            UpdatedDate = 0L
                        },
                        new
                        {
                            Id = new Guid("81ac10c1-b977-45c9-a637-a00654ef07e7"),
                            CreateDate = 0L,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Physical cash account.",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemDefault = true,
                            LastUpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Cash",
                            UpdatedDate = 0L
                        },
                        new
                        {
                            Id = new Guid("9de9f381-06e4-41f8-8269-f8cb76330cc9"),
                            CreateDate = 0L,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Brokerage or investment account.",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemDefault = true,
                            LastUpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Investment",
                            UpdatedDate = 0L
                        },
                        new
                        {
                            Id = new Guid("f95a4632-e98f-4c9b-b831-b14447e3e308"),
                            CreateDate = 0L,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Loan or other debt account.",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemDefault = true,
                            LastUpdatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Loan",
                            UpdatedDate = 0L
                        });
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint")
                        .HasColumnName("create_date");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deletion_indicator");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_default");

                    b.Property<Guid>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasColumnOrder(2);

                    b.Property<long>("UpdatedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_payment_methods");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("ix_payment_methods_user_id_is_active");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_methods_user_id_name");

                    b.ToTable("payment_methods", "finance");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.RecurringTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint")
                        .HasColumnName("create_date");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<long?>("EndDate")
                        .HasColumnType("bigint")
                        .HasColumnName("end_date");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deletion_indicator");

                    b.Property<Guid>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("merchant_name");

                    b.Property<long>("NextRunDate")
                        .HasColumnType("bigint")
                        .HasColumnName("next_run_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("PaymentMethodId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_method_id");

                    b.Property<long>("StartDate")
                        .HasColumnType("bigint")
                        .HasColumnName("start_date");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<long>("UpdatedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_recurring_transactions");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_recurring_transactions_account_id");

                    b.HasIndex("BudgetId")
                        .HasDatabaseName("ix_recurring_transactions_budget_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_recurring_transactions_category_id");

                    b.HasIndex("PaymentMethodId")
                        .HasDatabaseName("ix_recurring_transactions_payment_method_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_recurring_transactions_user_id");

                    b.HasIndex("IsActive", "NextRunDate")
                        .HasDatabaseName("ix_recurring_transactions_is_active_next_run_date");

                    b.ToTable("recurring_transactions", "finance");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<decimal>("AccountBalanceAfterTransaction")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("account_balance_after_transaction");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint")
                        .HasColumnName("create_date");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deletion_indicator");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<Guid>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<Guid?>("LinkedTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_transaction_id");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("merchant_name");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("PaymentMethodId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_method_id");

                    b.Property<Guid>("RecurringTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurring_transaction_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<long>("TransactionDate")
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_date");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<long>("UpdatedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("BudgetId")
                        .HasDatabaseName("ix_transactions_budget_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_transactions_category_id");

                    b.HasIndex("LinkedTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_transactions_linked_transaction_id")
                        .HasFilter("\"LinkedTransactionId\" IS NOT NULL");

                    b.HasIndex("PaymentMethodId")
                        .HasDatabaseName("ix_transactions_payment_method_id");

                    b.HasIndex("AccountId", "TransactionDate")
                        .HasDatabaseName("ix_transactions_account_id_transaction_date");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_transactions_user_id_status");

                    b.HasIndex("UserId", "TransactionDate")
                        .HasDatabaseName("ix_transactions_user_id_transaction_date");

                    b.ToTable("transactions", "finance");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint")
                        .HasColumnName("create_date");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("bigint")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deletion_indicator");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<Guid>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<long>("UpdatedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_date");

                    b.Property<long?>("UsedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_email_verification_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_email_verification_tokens_token_hash");

                    b.HasIndex("UserId", "IsRevoked", "ExpiresAt")
                        .HasDatabaseName("ix_email_verification_tokens_user_id_is_revoked_expires_at");

                    b.ToTable("email_verification_tokens", "identity");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint")
                        .HasColumnName("create_date");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("bigint")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deletion_indicator");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<Guid>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<long>("UpdatedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_date");

                    b.Property<long?>("UsedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_password_reset_tokens_token_hash");

                    b.HasIndex("UserId", "IsRevoked", "ExpiresAt")
                        .HasDatabaseName("ix_password_reset_tokens_user_id_is_revoked_expires_at");

                    b.ToTable("password_reset_tokens", "identity");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint")
                        .HasColumnName("create_date");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("bigint")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deletion_indicator");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<Guid>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("revocation_reason");

                    b.Property<long?>("RevokedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<long>("UpdatedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "IsRevoked", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_user_id_is_revoked_expires_at");

                    b.ToTable("refresh_tokens", "identity");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_name");

                    b.ToTable("roles", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e04d972-5cde-4156-8ac4-b5659549236b"),
                            Name = "User"
                        },
                        new
                        {
                            Id = new Guid("aa911248-931b-4cb2-9a65-451081aa3976"),
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<long?>("EmailVerifiedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("profile_image_url");

                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("7e04d972-5cde-4156-8ac4-b5659549236b"))
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.ReferenceSchema.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint")
                        .HasColumnName("create_date");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deletion_indicator");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_default");

                    b.Property<Guid>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasColumnOrder(2);

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<long>("UpdatedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_date");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("ix_categories_user_id_is_active");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_user_id_name");

                    b.ToTable("categories", "reference");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.BudgetingSchema.Budget", b =>
                {
                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.User", "OwnerUser")
                        .WithMany("OwnedBudgets")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budgets_users_owner_user_id");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.BudgetingSchema.BudgetCategory", b =>
                {
                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.BudgetingSchema.Budget", "Budget")
                        .WithMany("BudgetCategories")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_categories_budgets_budget_id");

                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.ReferenceSchema.Category", "Category")
                        .WithMany("BudgetCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_categories_categories_category_id");

                    b.Navigation("Budget");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.BudgetingSchema.BudgetMember", b =>
                {
                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.BudgetingSchema.Budget", "Budget")
                        .WithMany("Members")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_members_budgets_budget_id");

                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.User", "User")
                        .WithMany("BudgetMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_members_users_user_id");

                    b.Navigation("Budget");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.Account", b =>
                {
                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.AccountType", "AccountType")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_account_types_account_type_id");

                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_users_user_id");

                    b.Navigation("AccountType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.AccountType", b =>
                {
                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.User", "User")
                        .WithMany("AccountTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_account_types_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.PaymentMethod", b =>
                {
                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.User", "User")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_methods_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.RecurringTransaction", b =>
                {
                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_transactions_accounts_account_id");

                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.BudgetingSchema.Budget", "Budget")
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recurring_transactions_budgets_budget_id");

                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.ReferenceSchema.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recurring_transactions_categories_category_id");

                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recurring_transactions_payment_methods_payment_method_id");

                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.User", "User")
                        .WithMany("RecurringTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_transactions_users_user_id");

                    b.Navigation("Account");

                    b.Navigation("Budget");

                    b.Navigation("Category");

                    b.Navigation("PaymentMethod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.Transaction", b =>
                {
                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_accounts_account_id");

                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.BudgetingSchema.Budget", "Budget")
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transactions_budgets_budget_id");

                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.ReferenceSchema.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_categories_category_id");

                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.Transaction", "LinkedTransaction")
                        .WithOne()
                        .HasForeignKey("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.Transaction", "LinkedTransactionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transactions_transactions_linked_transaction_id");

                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.PaymentMethod", "PaymentMethod")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transactions_payment_methods_payment_method_id");

                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_users_user_id");

                    b.Navigation("Account");

                    b.Navigation("Budget");

                    b.Navigation("Category");

                    b.Navigation("LinkedTransaction");

                    b.Navigation("PaymentMethod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.EmailVerificationToken", b =>
                {
                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.User", "User")
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.PasswordResetToken", b =>
                {
                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.RefreshToken", b =>
                {
                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.User", b =>
                {
                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.ReferenceSchema.Category", b =>
                {
                    b.HasOne("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_categories_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.BudgetingSchema.Budget", b =>
                {
                    b.Navigation("BudgetCategories");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.AccountType", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.FinanceSchema.PaymentMethod", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.IdentitySchema.User", b =>
                {
                    b.Navigation("AccountTypes");

                    b.Navigation("Accounts");

                    b.Navigation("BudgetMemberships");

                    b.Navigation("Categories");

                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("OwnedBudgets");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("PaymentMethods");

                    b.Navigation("RecurringTransactions");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Expensify.DataAccessLayer.Entities.Models.ReferenceSchema.Category", b =>
                {
                    b.Navigation("BudgetCategories");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
